name: Run the bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
    - cron: "30 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
jobs:
  yeet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm start
        env:
          RANDOMLY_RUN: ${{ github.event_name == 'schedule' }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
